# Generated by Django 4.0.4 on 2022-04-16 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstatico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandado',
            name='demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstatico.demanda'),
        ),
        migrations.AlterField(
            model_name='demandante',
            name='demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appstatico.demanda'),
        ),
    ]
