# Generated by Django 4.0.4 on 2022-04-16 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appstatico', '0002_alter_demandado_demanda_alter_demandante_demanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('correo', models.CharField(blank=True, max_length=35, null=True)),
                ('password', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='demanda',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstatico.profile'),
        ),
    ]
